# Generated by Django 5.1 on 2024-09-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('seller', models.CharField(max_length=255)),
                ('seller_address', models.TextField()),
                ('item_name', models.CharField(max_length=255)),
                ('item_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('code', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=255)),
                ('customer_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
            ],
            options={
                'db_table': 'sales_records',
            },
        ),
    ]
